-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    firstname character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    CONSTRAINT admins_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL DEFAULT nextval('cities_city_id_seq'::regclass),
    city_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.cover_letters
(
    letter_id bigint NOT NULL DEFAULT nextval('cover_letter_letter_id_seq'::regclass),
    creation_date timestamp without time zone NOT NULL,
    letter_content character varying(1000000) COLLATE pg_catalog."default",
    letter_name character varying(255) COLLATE pg_catalog."default",
    employee_id bigint,
    CONSTRAINT cover_letter_pkey PRIMARY KEY (letter_id)
);

CREATE TABLE IF NOT EXISTS public.educations
(
    education_id bigint NOT NULL DEFAULT nextval('educations_education_id_seq'::regclass),
    city_name character varying(255) COLLATE pg_catalog."default",
    degree_type double precision,
    department character varying(255) COLLATE pg_catalog."default",
    description character varying(1000000) COLLATE pg_catalog."default",
    education_language character varying(255) COLLATE pg_catalog."default",
    education_level character varying(255) COLLATE pg_catalog."default",
    education_type character varying(255) COLLATE pg_catalog."default",
    ending_date date,
    faculty character varying(255) COLLATE pg_catalog."default",
    graduation_degree double precision,
    is_continue boolean,
    starting_date date,
    university_name character varying(255) COLLATE pg_catalog."default",
    resume_id bigint,
    CONSTRAINT educations_pkey PRIMARY KEY (education_id)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    firstname character varying(255) COLLATE pg_catalog."default",
    identity_number character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default",
    year_of_birth integer,
    employee_id bigint NOT NULL,
    address character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    postal_code character varying(255) COLLATE pg_catalog."default",
    province character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
    CONSTRAINT uk_r3hlvtweaf7xpyrg1sbemc166 UNIQUE (identity_number)
);

CREATE TABLE IF NOT EXISTS public.employers
(
    company_name character varying(255) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    CONSTRAINT employers_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.experiences
(
    experience_id bigint NOT NULL DEFAULT nextval('experiences_experience_id_seq'::regclass),
    city_name character varying(255) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    company_sector character varying(255) COLLATE pg_catalog."default",
    end_date date,
    start_date date,
    job_description character varying(1000000) COLLATE pg_catalog."default",
    title_id integer,
    resume_id bigint,
    working_type_id integer,
    CONSTRAINT experiences_pkey PRIMARY KEY (experience_id)
);

CREATE TABLE IF NOT EXISTS public.job_posting_applications
(
    application_id bigint NOT NULL DEFAULT nextval('job_posting_applications_application_id_seq'::regclass),
    applied_date timestamp without time zone NOT NULL,
    letter_content character varying(1000000) COLLATE pg_catalog."default",
    letter_id bigint,
    letter_name character varying(255) COLLATE pg_catalog."default",
    employee_id bigint,
    job_posting_id bigint,
    resume_id bigint,
    CONSTRAINT job_posting_applications_pkey PRIMARY KEY (application_id)
);

CREATE TABLE IF NOT EXISTS public.job_postings
(
    job_posting_id bigint NOT NULL DEFAULT nextval('job_postings_job_posting_id_seq'::regclass),
    application_deadline date,
    available_position integer,
    is_active boolean,
    job_description character varying(1000000) COLLATE pg_catalog."default",
    job_summary character varying(255) COLLATE pg_catalog."default",
    publication_date timestamp without time zone NOT NULL,
    salary_max character varying(255) COLLATE pg_catalog."default",
    salary_min character varying(255) COLLATE pg_catalog."default",
    city_id integer,
    user_id bigint,
    title_id integer,
    working_type_id integer,
    CONSTRAINT job_postings_pkey PRIMARY KEY (job_posting_id)
);

CREATE TABLE IF NOT EXISTS public.job_titles
(
    title_id integer NOT NULL DEFAULT nextval('job_titles_title_id_seq'::regclass),
    job_title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT job_titles_pkey PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS public.language_list
(
    language_id bigint NOT NULL DEFAULT nextval('language_list_language_id_seq'::regclass),
    language_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT language_list_pkey PRIMARY KEY (language_id)
);

CREATE TABLE IF NOT EXISTS public.languages
(
    language_id integer NOT NULL DEFAULT nextval('languages_language_id_seq'::regclass),
    language_level character varying(255) COLLATE pg_catalog."default",
    language_name character varying(255) COLLATE pg_catalog."default",
    resume_id bigint,
    CONSTRAINT languages_pkey PRIMARY KEY (language_id)
);

CREATE TABLE IF NOT EXISTS public.refreshtoken
(
    id bigint NOT NULL,
    expiry_date timestamp without time zone NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    CONSTRAINT refreshtoken_pkey PRIMARY KEY (id),
    CONSTRAINT uk_or156wbneyk8noo4jstv55ii3 UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.resumes
(
    resume_id bigint NOT NULL DEFAULT nextval('resumes_resume_id_seq'::regclass),
    creation_date timestamp without time zone NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    github_address character varying(255) COLLATE pg_catalog."default",
    linkedin_address character varying(255) COLLATE pg_catalog."default",
    military_status character varying(255) COLLATE pg_catalog."default",
    personal_website character varying(255) COLLATE pg_catalog."default",
    postponed_date date,
    resume_name character varying(255) COLLATE pg_catalog."default",
    employee_id bigint,
    driving_licence character varying(255) COLLATE pg_catalog."default",
    job_title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT resumes_pkey PRIMARY KEY (resume_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.skills
(
    skill_id integer NOT NULL DEFAULT nextval('skills_skill_id_seq'::regclass),
    skill_name character varying(255) COLLATE pg_catalog."default",
    resume_id bigint,
    CONSTRAINT skills_pkey PRIMARY KEY (skill_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    profile_photo_url character varying(255) COLLATE pg_catalog."default",
    user_name character varying(255) COLLATE pg_catalog."default",
    verification_expiry timestamp without time zone,
    verified boolean NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_k8d0f2n7n88w1a16yhua64onx UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS public.working_types
(
    working_type_id integer NOT NULL DEFAULT nextval('working_types_working_type_id_seq'::regclass),
    type_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT working_types_pkey PRIMARY KEY (working_type_id)
);

ALTER TABLE IF EXISTS public.admins
    ADD CONSTRAINT fkgc8dtql9mkq268detxiox7fpm FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS admins_pkey
    ON public.admins(user_id);


ALTER TABLE IF EXISTS public.cover_letters
    ADD CONSTRAINT fk22xj2gov3ufxh26q9h9akhkmc FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.educations
    ADD CONSTRAINT fko2o6l2a14fq9hkoo9io2st374 FOREIGN KEY (resume_id)
    REFERENCES public.resumes (resume_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT fkhhbl7vhnb6o6h5u71nwdcme6q FOREIGN KEY (employee_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employees_pkey
    ON public.employees(employee_id);


ALTER TABLE IF EXISTS public.employers
    ADD CONSTRAINT fk6abfx371o1dsomsi0jstr0utl FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employers_pkey
    ON public.employers(user_id);


ALTER TABLE IF EXISTS public.experiences
    ADD CONSTRAINT fk9s73d9jh5wbuepmlhnjq0i0jk FOREIGN KEY (working_type_id)
    REFERENCES public.working_types (working_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.experiences
    ADD CONSTRAINT fkhhketaibrcmn9m582gb8jwipv FOREIGN KEY (resume_id)
    REFERENCES public.resumes (resume_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.experiences
    ADD CONSTRAINT fkim8yao1lul4dw2r3lyvtfmfyv FOREIGN KEY (title_id)
    REFERENCES public.job_titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_posting_applications
    ADD CONSTRAINT fkmowmol879xw2suv17aag5dems FOREIGN KEY (job_posting_id)
    REFERENCES public.job_postings (job_posting_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_posting_applications
    ADD CONSTRAINT fkndq7hag31jei1m91b1jvfn7jh FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_posting_applications
    ADD CONSTRAINT fkovfeirfwoo9texukbtleo41u7 FOREIGN KEY (resume_id)
    REFERENCES public.resumes (resume_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_postings
    ADD CONSTRAINT fk480br7ldl52spdw0vpdhl4dtu FOREIGN KEY (user_id)
    REFERENCES public.employers (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_postings
    ADD CONSTRAINT fka9m1jaxwd3dqyfdw856vrg4fr FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_postings
    ADD CONSTRAINT fkr0hf0cwpn1k20arh0hl1a5ubd FOREIGN KEY (working_type_id)
    REFERENCES public.working_types (working_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job_postings
    ADD CONSTRAINT fkrqowpmjq7cogvjag1efignu0i FOREIGN KEY (title_id)
    REFERENCES public.job_titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.languages
    ADD CONSTRAINT fkgww7w2h4ius3ypgibqm5bo5ap FOREIGN KEY (resume_id)
    REFERENCES public.resumes (resume_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refreshtoken
    ADD CONSTRAINT fka652xrdji49m4isx38pp4p80p FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resumes
    ADD CONSTRAINT fklybsj04tcqkh2xbd00yl04t5y FOREIGN KEY (employee_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skills
    ADD CONSTRAINT fk8lvpcbo92i34gfp0h0ydq5vcm FOREIGN KEY (resume_id)
    REFERENCES public.resumes (resume_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;